### ISSUE TITLE
LED_PORT_DIR not defined?

### ISSUE THREAD

**Issue by bj80421** [maniacbug/ZMAC#1]
Attempting to compile Star_Nobeacon gives this error:
/usr/share/arduino/libraries/ZMAC/pal_board.c: In function 'pal_led_init':
/usr/share/arduino/libraries/ZMAC/pal_board.c:16:5: error: 'LED_PORT_DIR' undeclared (first use in this function)
/usr/share/arduino/libraries/ZMAC/pal_board.c:16:5: note: each undeclared identifier is reported only once for each function it appears in

This is arduino 0021 which you have not tested with.

**Comment by maniacbug** [comment]
Ah yes I noticed that got undefined somehow. I'll push up that fix, its an easy one .

-----Original Message-----
From: bj80421
Sent: Wednesday, July 27, 2011 10:10 PM
To: maniacbug@ymail.com
Subject: [ZMAC] LED_PORT_DIR not defined? (#1)

Attempting to compile Star_Nobeacon gives this error:
/usr/share/arduino/libraries/ZMAC/pal_board.c: In function 'pal_led_init':
/usr/share/arduino/libraries/ZMAC/pal_board.c:16:5: error: 'LED_PORT_DIR' undeclared (first use in this function)
/usr/share/arduino/libraries/ZMAC/pal_board.c:16:5: note: each undeclared identifier is reported only once for each function it appears in

This is arduino 0021 which you have not tested with.

## 

Reply to this email directly or view it on GitHub:
https://github.com/maniacbug/ZMAC/issues/1

**Comment by maniacbug** [comment]
FIxed.  https://github.com/maniacbug/ZMAC/commit/3792a920198df2a9ffd6e6f208e96428bc17ef4a
