### ISSUE TITLE
Example not compiling

### ISSUE THREAD

**Issue by edmont** [maniacbug/ZMAC#2]
Software versions:

Windows 7 (under VirtualBox)
Arduino 0.22
C:\Atmel\MAC_v_2_7_0\
gawk-3.1.6-1
maniacbug-ZMAC-0.4-0-gec02e54

I have several Zigduinos in which I could upload the "Blink" sketch successfully. I followed the installing instructions #1 to #11 without problems, but when trying to verify I got:

In file included from C:\Users\Eduardo\Desktop\arduino-0022\libraries\ZMAC/app_config.h:26,
                 from C:\Users\Eduardo\Desktop\arduino-0022\libraries\ZMAC/pal.h:39,
                 from example_main.c:27:
C:\Users\Eduardo\Desktop\arduino-0022\libraries\ZMAC/stack_config.h:153:35: error: mac_msg_type_data_ind.h: No such file or directory

What could be the problem? Thanks.

**Comment by edmont** [comment]
Solved!

I manually copied "C:\Atmel\MAC_v_2_7_0\MAC\Inc\mac_msg_type_data_ind.h" to "C:\Users\Eduardo\Desktop\arduino-0022\libraries\ZMAC" and the example compiled and worked properly with two Zigduinos. This is maybe a new file in MAC 2.7.0 version.

Time to start developing my application :)

Thanks for the porting!

**Comment by maniacbug** [comment]
Hey.  could you send the entire compiler output?  hold down shift then verify.  also send app config.h.
Sent from my Nokia phone
-----Original Message-----
From: edmont
Sent:  24/08/2011, 13:12 
To: maniacbug@ymail.com
Subject: [ZMAC] Example not compiling (#2)

Software versions:

Windows 7 (under VirtualBox)
Arduino 0.22
C:\Atmel\MAC_v_2_7_0\
gawk-3.1.6-1
maniacbug-ZMAC-0.4-0-gec02e54

I have several Zigduinos in which I could upload the "Blink" sketch successfully. I followed the installing instructions #1 to #11 without problems, but when trying to verify I got:

In file included from C:\Users\Eduardo\Desktop\arduino-0022\libraries\ZMAC/app_config.h:26,
                 from C:\Users\Eduardo\Desktop\arduino-0022\libraries\ZMAC/pal.h:39,
                 from example_main.c:27:
C:\Users\Eduardo\Desktop\arduino-0022\libraries\ZMAC/stack_config.h:153:35: error: mac_msg_type_data_ind.h: No such file or directory

What could be the problem? Thanks.

## 

Reply to this email directly or view it on GitHub:
https://github.com/maniacbug/ZMAC/issues/2

**Comment by edmont** [comment]
Compiler output:

C:\Users\Eduardo\Desktop\arduino-0022\hardware\tools\avr\bin\avr-gcc -c -g -Os -w -ffunction-sections -fdata-sections -mmcu=atmega128rfa1 -DF_CPU=16000000L -DARDUINO=22 -IC:\Users\Eduardo\Desktop\arduino-0022\hardware\arduino\cores\zigduino -IC:\Users\Eduardo\Desktop\arduino-0022\libraries\ZMAC C:\Users\Eduardo\AppData\Local\Temp\build1718983876907824436.tmp\example_main.c -oC:\Users\Eduardo\AppData\Local\Temp\build1718983876907824436.tmp\example_main.c.o 
In file included from C:\Users\Eduardo\Desktop\arduino-0022\libraries\ZMAC/app_config.h:26,
                 from C:\Users\Eduardo\Desktop\arduino-0022\libraries\ZMAC/pal.h:39,
                 from C:\Users\Eduardo\AppData\Local\Temp\build1718983876907824436.tmp\example_main.c:27:
C:\Users\Eduardo\Desktop\arduino-0022\libraries\ZMAC/stack_config.h:153:35: error: mac_msg_type_data_ind.h: No such file or directory

app_config.h

#include <ZMAC.h>
/**
- @file app_config.h
  *
- @brief These are application-specific resources which are used
-        in the example application of the device in addition to the
-        underlaying stack.
  *
- $Id: app_config.h 27459 2011-06-23 13:48:37Z yogesh.bellan $
  *
- @author    Atmel Corporation: http://www.atmel.com
- @author    Support email: avr@atmel.com
  _/
  /_
- Copyright (c) 2009, Atmel Corporation All rights reserved.
  *
- Licensed under Atmel's Limited License Agreement --> EULA.txt
  */

/\* Prevent double inclusion */
#ifndef APP_CONFIG_H
#define APP_CONFIG_H

/\* === Includes ============================================================= */

#include "stack_config.h"

/\* === Macros =============================================================== */

/*\* @brief This is the first timer identifier of the application.
 *
-  The value of this identifier is an increment of the largest identifier
-  value used by the MAC.
  */
  #if (NUMBER_OF_TOTAL_STACK_TIMERS == 0)
  #define APP_FIRST_TIMER_ID          (0)
  #else
  #define APP_FIRST_TIMER_ID          (LAST_STACK_TIMER_ID + 1)
  #endif

/\* === Types ================================================================ */

/*\* Timer ID's used by the Application _/
typedef enum
{
    /_ App Timers start from APP_FIRST_TIMER_ID */

```
/** Application timer id used by the device to send data */
TIMER_TX_DATA = (APP_FIRST_TIMER_ID),

/** Application timer id used to switch off LED */
TIMER_LED_OFF = (APP_FIRST_TIMER_ID + 1)
```

,APP_TIMER_INDIRECT_DATA = (APP_FIRST_TIMER_ID),
APP_TIMER_POLL_DATA = (APP_FIRST_TIMER_ID),
APP_TIMER_LED_OFF = (APP_FIRST_TIMER_ID + 1)
} app_timer_t;

/*\* Defines the number of timers used by the application. */
#define NUMBER_OF_APP_TIMERS        (2)

/*\* Defines the total number of timers used by the application and the layers below. */
#define TOTAL_NUMBER_OF_TIMERS      (NUMBER_OF_APP_TIMERS + NUMBER_OF_TOTAL_STACK_TIMERS)

/*\* Defines the number of additional large buffers used by the application */
#define NUMBER_OF_LARGE_APP_BUFS    (0)

/*\* Defines the number of additional small buffers used by the application */
#define NUMBER_OF_SMALL_APP_BUFS    (0)

/**
-  Defines the total number of large buffers used by the application and the
-  layers below.
  */
  #define TOTAL_NUMBER_OF_LARGE_BUFS  (NUMBER_OF_LARGE_APP_BUFS + NUMBER_OF_LARGE_STACK_BUFS)

/**
-  Defines the total number of small buffers used by the application and the
-  layers below.
  */
  #define TOTAL_NUMBER_OF_SMALL_BUFS  (NUMBER_OF_SMALL_APP_BUFS + NUMBER_OF_SMALL_STACK_BUFS)

/**
-  Defines the total number of small and large buffers used by the application and the
-  layers below.
  */
  #define TOTAL_NUMBER_OF_BUFS        (TOTAL_NUMBER_OF_LARGE_BUFS + TOTAL_NUMBER_OF_SMALL_BUFS)

/**
- Defines the USB transmit buffer size
  */
  #define USB_TX_BUF_SIZE             (10)

/**
- Defines the USB receive buffer size
  */
  #define USB_RX_BUF_SIZE             (10)

/*
- USB-specific definitions
  */

/*
- USB Vendor ID (16-bit number)
  _/
  #define USB_VID                 0x03EB /_ Atmel's USB vendor ID */

/*
- USB Product ID (16-bit number)
  _/
  #define USB_PID                 0x2018 /_ RZ USB stick product ID */

/*
- USB Release number (BCD format, two bytes)
  _/
  #define USB_RELEASE             { 0x00, 0x01 } /_ 01.00 */

/*
- Maximal number of UTF-16 characters used in any of the strings
- below.  This is only used for compilers that cannot handle the
- initialization of flexible array members within structs.
  */
  #define USB_STRING_SIZE         10

/*
- String representation for the USB vendor name.
  */
  #define USB_VENDOR_NAME L"ATMEL"

/*
- String representation for the USB product name.
  */
  #define USB_PRODUCT_NAME L"RZUSBSTICK"

/**
- Defines the UART transmit buffer size
  */
  #define UART_MAX_TX_BUF_LENGTH      (10)

/**
- Defines the UART receive buffer size
  */
  #define UART_MAX_RX_BUF_LENGTH      (10)

/\* Offset of IEEE address storage location within EEPROM */
#define EE_IEEE_ADDR                (0)

/\* === Externals ============================================================ */

/\* === Prototypes =========================================================== */

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /\* extern "C" */
#endif

#endif /\* APP_CONFIG_H _/
/_ EOF */

**Comment by maniacbug** [comment]
Hey, glad to see you got it to work.  Yes indeed, ZMAC only works with 2.6.1.  This is an unfortunate problem with the approach of copying files around.  Every time they release a new stack, ZMAC is broken and would need to be updated.
